options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/sunfish/server'
      - '.'

  # Step 2 (Optional): Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/sunfish/server'

# Define any images built/pushed to be used later (e.g., Cloud Run deployment)
images:
  - 'europe-west9-docker.pkg.dev/$PROJECT_ID/sunfish/server'
