version: '3'
services:
  sunfish:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    # Mount local files into the container
    volumes:
      - ./server.py:/usr/src/app/server.py
      - ./sunfish.py:/usr/src/app/sunfish.py
      - ./tools:/usr/src/app/tools
    # Expose and publish port 5000
    ports:
      - "5500:5500"
    # Command to start your Flask app (assuming server.py is the entry script)
    command: python /usr/src/app/server.py
    environment:
      - debug=True
      - PYTHONUNBUFFERED=1  # Disable buffering for real-time logs

