#!/usr/bin/env python3
"""
Generate csrc/tables.h from sunfish.py PST data.

Reads the padded PST tables after sunfish.py processes them,
then emits a C header with static arrays for use by the C extension.

Usage:
    python scripts/gen_tables.py > csrc/tables.h
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

# Force no C extension during import (we just need the tables)
os.environ["SUNFISH_NO_C"] = "1"
import sunfish


# Piece index mapping: must match PIECE_INDEX in the generated header
PIECE_ORDER = ["P", "N", "B", "R", "Q", "K", "O", "J"]
PIECE_CHARS = {
    "P": 0, "A": 0,  # pawns share index
    "N": 1, "C": 1,  # knights
    "B": 2, "D": 2,  # bishops
    "R": 3, "T": 3,  # rooks
    "Q": 4, "X": 4,  # queens
    "K": 5, "Y": 5,  # kings
    "O": 6,           # rocks
    "J": 7,           # ninja knight (own index, higher piece value than N)
}


def fmt_array(values, name, ctype="int", per_line=10):
    """Format a C array declaration."""
    lines = [f"static const {ctype} {name}[] = {{"]
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        line = "    " + ", ".join(f"{v:>6}" for v in chunk) + ","
        lines.append(line)
    lines.append("};")
    return "\n".join(lines)


def main():
    print("/* Auto-generated by scripts/gen_tables.py — do not edit */")
    print("#ifndef SUNFISH_TABLES_H")
    print("#define SUNFISH_TABLES_H")
    print()

    # Piece values
    piece_values = [sunfish.piece[p] for p in PIECE_ORDER]
    print(fmt_array(piece_values, "PIECE_VALUE"))
    print()

    # PST tables: 8 pieces x 120 positions
    print("/* PST[piece_index][board_position] — padded 120-element tables */")
    print(f"static const int PST[{len(PIECE_ORDER)}][120] = {{")
    for pi, p in enumerate(PIECE_ORDER):
        table = sunfish.pst[p]
        assert len(table) == 120, f"PST[{p}] has {len(table)} elements, expected 120"
        print(f"    /* {p} (index {pi}) */")
        print("    {")
        for row in range(12):
            vals = table[row * 10 : row * 10 + 10]
            print("        " + ", ".join(f"{v:>6}" for v in vals) + ",")
        print("    },")
    print("};")
    print()

    # PIECE_INDEX lookup: char -> piece table index
    # Initialize all to -1 (invalid)
    print("/* Map piece char (0-127) to PST index. -1 = not a piece. */")
    print("static const int PIECE_INDEX[128] = {")
    idx = [-1] * 128
    for ch, pi in PIECE_CHARS.items():
        idx[ord(ch)] = pi
    for row in range(0, 128, 16):
        chunk = idx[row : row + 16]
        print("    " + ", ".join(f"{v:>2}" for v in chunk) + ",")
    print("};")
    print()

    # Also generate uppercase version for captures (lowercase piece -> uppercase index)
    print("/* Map lowercase piece char to PST index (for capture scoring). */")
    print("static const int PIECE_INDEX_LOWER[128] = {")
    idx_lower = [-1] * 128
    for ch, pi in PIECE_CHARS.items():
        idx_lower[ord(ch.lower())] = pi
    for row in range(0, 128, 16):
        chunk = idx_lower[row : row + 16]
        print("    " + ", ".join(f"{v:>2}" for v in chunk) + ",")
    print("};")
    print()

    print("#endif /* SUNFISH_TABLES_H */")


if __name__ == "__main__":
    main()
